import sys
sys.path.insert(1, '/Users/marcusallen/Documents/GitHub/causal-set-simulations/causal_sets')
from dynamical_shell import *
start1 =time.time()
causet = DynamicalShellHorizon(rho=300)
causet.number_points()
print(causet.n)
causet.coordinates()
above, below = causet.cuts2(causet.points,causet.radius)
rels_above =get_relations_above(N=causet.n, points=causet.points, above=above)
rels_below =get_relations_below(N=causet.n, points=causet.points, below=below)
count = interval_size(rels_above,rels_below)
SMI = SMI_calc(count, causet.dim, 10)
print(SMI)
print('Time to run',time_to_run(start1))